name: ri_go_demo
description: A demo project, that uses riverpod and go_router.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.13
  intl: ^0.18.0
  # riverpod stuff
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0

  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  go_router: ^11.1.3
  gap: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  # riverpod generator/dev stuff
  riverpod_generator:
  riverpod_lint:
  # import custom_lint too as riverpod_lint depends on it
  custom_lint:
  very_good_analysis: ^5.1.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # for localization
  generate: true
